version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn medical_calculator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
    - static_volume:/var/www/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: